spring.application.name=notificacion-servicio
server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/notificacion_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.foodfast.notificacion_servicio=INFO
logging.level.org.hibernate.SQL=DEBUG

# Seguridad futura con JWT. No se activa todavía para no bloquear pruebas en Postman.
# jwt.secret=FoodFastClaveJWTUltraSegura2026ConMasDe42CaracteresParaFirmarTokens
