spring.application.name=pedido-servicio

server.port=8082    

spring.datasource.url=jdbc:mysql://localhost:3306/pedido_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false

app.inventario-service.url=http://localhost:8082